version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: tododb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro

  backend:
    build: .
    environment:
      DATABASE_URL: postgres://user:password@postgres:5432/tododb
    ports:
      - "3001:3001"
    depends_on:
      - postgres
    command: ["npx", "nodemon", "src/server.ts"]


volumes:
  postgres_data: