version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: tododb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./back-end/init.sql:/docker-entrypoint-initdb.d/init.sql:ro

  backend:
    build:
      context: ./back-end
    environment:
      DATABASE_URL: postgres://user:password@postgres:5432/tododb
    ports:
      - "3001:3001"
    depends_on:
      - postgres
    volumes:
      - ./back-end:/app
    command: ["npx", "nodemon", "src/server.ts"]

  frontend:
    build:
      context: ./front-end
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./front-end:/app

volumes:
  postgres_data:
